# Generated by Django 5.2.4 on 2025-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_exchangeproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="condition",
            field=models.CharField(choices=[("new", "новый"), ("used", "б/у")]),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ожидает"),
                    ("accepted", "принята"),
                    ("rejected", "отклонена"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
